import React, { useEffect, useMemo, useState } from 'react';
import { Code, GitCommit, Github, Link2, RefreshCw, Search } from 'lucide-react';
import { github, GitHubBranch, GitHubCommit, GitHubContent, GitHubRepo, GitHubResourceLink, GitHubSearchResult } from '../lib/github';
import FileViewer from './github/FileViewer';
import GitHubExplorer from './github/GitHubExplorer';
import RepoCard from './github/RepoCard';

type Tab = 'repos' | 'resources' | 'commits' | 'search';

export default function GitHubDashboard() {
  const [repos, setRepos] = useState<GitHubRepo[]>([]); const [links, setLinks] = useState<GitHubResourceLink[]>([]); const [tab, setTab] = useState<Tab>('repos');
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [repoSearch, setRepoSearch] = useState('');
  const [selectedRepo, setSelectedRepo] = useState<GitHubRepo | null>(null); const [branches, setBranches] = useState<GitHubBranch[]>([]); const [branch, setBranch] = useState('');
  const [selectedFile, setSelectedFile] = useState<{ repo: string; file: GitHubContent } | null>(null); const [commits, setCommits] = useState<GitHubCommit[]>([]); const [commitsLoading, setCommitsLoading] = useState(false);
  const [codeQuery, setCodeQuery] = useState(''); const [searchResults, setSearchResults] = useState<GitHubSearchResult | null>(null); const [searchLoading, setSearchLoading] = useState(false);

  const loadRepos = async () => { setLoading(true); setError(''); try { const [repoData, linkData] = await Promise.all([github.listRepositories({ perPage: 100 }), github.listResourceLinks().catch(() => [])]); setRepos(repoData); setLinks(linkData); setSelectedRepo(current => current || repoData[0] || null); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load GitHub repositories.'); } finally { setLoading(false); } };
  useEffect(() => { loadRepos(); }, []);
  useEffect(() => { if (!selectedRepo) return; setBranch(selectedRepo.default_branch); github.listBranches(selectedRepo.full_name).then(data => setBranches(data)).catch(() => setBranches([])); }, [selectedRepo]);
  useEffect(() => { if (!selectedRepo) return; setCommitsLoading(true); github.listCommits(selectedRepo.full_name, { branch, perPage: 10 }).then(setCommits).catch(() => setCommits([])).finally(() => setCommitsLoading(false)); }, [selectedRepo, branch]);

  const filteredRepos = useMemo(() => repos.filter(repo => [repo.name, repo.full_name, repo.description || '', repo.language || ''].join(' ').toLowerCase().includes(repoSearch.toLowerCase())), [repos, repoSearch]);
  const selectedRepoLinks = selectedRepo ? links.filter(link => link.github_repositories?.full_name === selectedRepo.full_name) : [];
  const tabs: Array<{ id: Tab; label: string }> = [{ id: 'repos', label: 'Repositories' }, { id: 'resources', label: 'Client Resources' }, { id: 'commits', label: 'Commits' }, { id: 'search', label: 'Code Search' }];
  const runSearch = async (event: React.FormEvent) => { event.preventDefault(); if (!codeQuery.trim() || !selectedRepo) return; setSearchLoading(true); setSearchResults(null); setError(''); try { setSearchResults(await github.searchCode(codeQuery.trim(), { repo: selectedRepo.full_name, branch, perPage: 20 })); } catch (err) { setError(err instanceof Error ? err.message : 'GitHub code search failed.'); } finally { setSearchLoading(false); } };

  return <div className="space-y-6">
    <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Github size={21} className="text-cyan-400" /><h2 className="text-lg font-display font-bold text-white">GitHub Integration Hub</h2></div><p className="mt-1 text-xs text-slate-400">Securely browse live GitHub repositories through the authenticated Supabase Edge Function.</p></div><button onClick={loadRepos} disabled={loading} className="self-start px-3 py-2 text-xs font-mono border border-[#1a2234] rounded-lg text-slate-300 hover:text-cyan-300 hover:border-cyan-500/40 disabled:opacity-50 flex items-center gap-2"><RefreshCw size={14} className={loading ? 'animate-spin' : ''} /> Refresh</button></div>
    {error && <div className="p-3 rounded-lg border border-red-900/70 bg-red-950/30 text-red-300 text-xs">{error}</div>}
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Repositories', repos.length], ['Resource Links', links.length], ['Private', repos.filter(r => r.private).length], ['Branches', branches.length]].map(([label, value]) => <div key={label} className="bg-[#0b0f19] border border-[#1a2234] rounded-xl p-4"><p className="text-[10px] text-slate-500 font-mono uppercase">{label}</p><p className="text-xl font-display font-extrabold text-white">{value}</p></div>)}</div>
    <div className="border-b border-[#1a2234] flex gap-1 overflow-x-auto">{tabs.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={`px-4 py-2.5 text-xs font-mono whitespace-nowrap border-b-2 ${tab === item.id ? 'border-cyan-400 text-cyan-300' : 'border-transparent text-slate-500 hover:text-slate-300'}`}>{item.label}</button>)}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[360px_1fr] gap-5">
      <aside className="space-y-3"><div className="relative"><Search size={14} className="absolute left-3 top-3 text-slate-500" /><input value={repoSearch} onChange={e => setRepoSearch(e.target.value)} placeholder="Search repositories..." className="w-full pl-9 pr-3 py-2.5 bg-[#0b0f19] border border-[#1a2234] rounded-xl text-xs text-white font-mono focus:outline-none focus:border-cyan-500" /></div>{loading ? [1,2,3].map(i => <div key={i} className="h-32 rounded-xl bg-[#0b0f19] border border-[#1a2234] animate-pulse" />) : filteredRepos.map(repo => <RepoCard key={repo.id} repo={repo} selected={selectedRepo?.id === repo.id} onSelect={setSelectedRepo} />)}{!loading && filteredRepos.length === 0 && <p className="p-6 text-center text-xs font-mono text-slate-500 bg-[#0b0f19] border border-[#1a2234] rounded-xl">No matching repositories.</p>}</aside>
      <main className="space-y-4">{selectedRepo ? <>
        <div className="bg-[#0b0f19] border border-[#1a2234] rounded-xl p-4 flex flex-col md:flex-row justify-between gap-3"><div><h3 className="text-white font-display font-bold">{selectedRepo.full_name}</h3><p className="text-xs text-slate-400 mt-1">{selectedRepo.description || 'No description provided.'}</p><p className="text-[10px] font-mono text-slate-500 mt-2">Default branch: {selectedRepo.default_branch} · {selectedRepo.private ? 'Private' : 'Public'} · {selectedRepo.language || 'Unknown language'}</p></div><a href={selectedRepo.html_url} target="_blank" rel="noreferrer" className="text-xs font-mono text-cyan-300 hover:underline">Open on GitHub →</a></div>
        {tab === 'repos' && <GitHubExplorer repo={selectedRepo.full_name} branch={branch} branches={branches} onBranchChange={setBranch} onFileSelect={file => setSelectedFile({ repo: selectedRepo.full_name, file })} />}
        {tab === 'resources' && <section className="bg-[#0b0f19] border border-[#1a2234] rounded-xl p-4 space-y-3"><h3 className="text-sm text-white font-display font-bold flex items-center gap-2"><Link2 size={16} className="text-cyan-400" /> Client/project associations</h3>{selectedRepoLinks.length === 0 ? <p className="text-xs text-slate-500">No Supabase resource links are configured for this repository yet.</p> : selectedRepoLinks.map(link => <button key={link.id} onClick={() => { setTab('repos'); setBranch(link.branch || selectedRepo.default_branch); }} className="w-full text-left p-3 rounded-lg bg-[#070a12] border border-[#1a2234] hover:border-cyan-500/40"><p className="text-xs text-white font-mono">{link.label || link.resource_type}</p><p className="text-[11px] text-slate-400">{link.clients?.company_name || 'Internal'} · {link.projects?.project_name || 'No project'} · /{link.directory_path}</p></button>)}</section>}
        {tab === 'commits' && <section className="bg-[#0b0f19] border border-[#1a2234] rounded-xl p-4 space-y-3"><h3 className="text-sm text-white font-display font-bold flex items-center gap-2"><GitCommit size={16} className="text-cyan-400" /> Recent commits</h3>{commitsLoading ? <p className="text-xs text-slate-500">Loading commits…</p> : commits.map(c => <a key={c.sha} href={c.html_url} target="_blank" rel="noreferrer" className="block p-3 rounded-lg bg-[#070a12] border border-[#1a2234] hover:border-cyan-500/40"><p className="text-xs text-white line-clamp-1">{c.commit.message}</p><p className="text-[10px] font-mono text-slate-500 mt-1">{c.sha.slice(0,7)} · {c.commit.author.name} · {new Date(c.commit.author.date).toLocaleString()}</p></a>)}{!commitsLoading && commits.length === 0 && <p className="text-xs text-slate-500">No commits available.</p>}</section>}
        {tab === 'search' && <section className="bg-[#0b0f19] border border-[#1a2234] rounded-xl p-4 space-y-3"><h3 className="text-sm text-white font-display font-bold flex items-center gap-2"><Code size={16} className="text-cyan-400" /> Code search</h3><form onSubmit={runSearch} className="flex gap-2"><input value={codeQuery} onChange={e => setCodeQuery(e.target.value)} placeholder="Search inside selected repository..." className="flex-1 px-3 py-2 bg-[#070a12] border border-[#1a2234] rounded-lg text-xs text-white font-mono" /><button disabled={searchLoading || !codeQuery.trim()} className="px-3 py-2 bg-cyan-500 text-slate-950 rounded-lg text-xs font-mono font-bold disabled:opacity-50">Search</button></form>{searchLoading && <p className="text-xs text-slate-500">Searching…</p>}{searchResults && <p className="text-[11px] font-mono text-slate-400">{searchResults.total_count} results</p>}{searchResults?.items.map(item => <a key={`${item.repository.full_name}:${item.sha}:${item.path}`} href={item.html_url} target="_blank" rel="noreferrer" className="block p-3 rounded-lg bg-[#070a12] border border-[#1a2234] hover:border-cyan-500/40"><p className="text-xs text-white">{item.path}</p><p className="text-[10px] font-mono text-slate-500">{item.repository.full_name}</p></a>)}</section>}
      </> : <p className="p-8 text-center text-xs text-slate-500 bg-[#0b0f19] border border-[#1a2234] rounded-xl">Select a repository to begin.</p>}</main>
    </div>
    {selectedFile && <FileViewer repo={selectedFile.repo} path={selectedFile.file.path} sha={selectedFile.file.sha} branch={branch} onClose={() => setSelectedFile(null)} />}
  </div>;
}
